chore: Add snafu::report to get better error detail (#694)
* chore: Add snafu::report to get better error detail

Before:

```
Error: ConstructHttpClient { source: reqwest::Error { kind: Builder, source: Normal(ErrorStack(])) } }
stream closed EOF for kuttl-test-assuring-molly/test-opa-server-default-wwhn7 (user-info-fetcher)
```

After:

```
Error: failed to construct http client

Caused by these errors (recent errors listed first):
  1: builder error
  2: OpenSSL error

stream closed EOF for kuttl-test-assuring-molly/test-opa-server-default-5pjjk (user-info-fetcher)
```

Co-authored-by: Techassi <git@techassi.dev>

* fix: Update native-tls due to regression

See: https://github.com/sfackler/rust-native-tls/releases/tag/v0.2.14

Co-authored-by: Techassi <git@techassi.dev>

---------

Co-authored-by: Techassi <git@techassi.dev>